version: "3.8"

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    # ⚠️ bỏ dòng 'image:' để tránh Portainer cố pull
    volumes:
      # nên dùng đường dẫn tuyệt đối phía host cho dễ tìm file
      - /data/dw/pdf-out:/app/pdf-out
    environment:
      - PAUSE_MS=800
      - CONCURRENCY=3
      - SCOPE_PREFIX=/docs/
      - START_URL=https://knowledgecenter.docuware.com/docs/
    command: ["node", "export-docuware.mjs"]
    restart: "no"

  # (tạm thời) bỏ ofelia để test chạy 1 lượt cho xong
